### ISSUE TITLE
Custom monitor definitions are persisted to other monitors

### ISSUE THREAD

**Issue by mjhuber** [reactiveops/rodd#32]
When custom monitors are defined, definitions are persisted to subsequent monitors.  For example, given this rodd file, the `kubernetes.cluster_memory` monitor would have the notification correctly defined as `@foo`:

```yaml
definitions:
  notifications: "@foo"
monitors:
  - source: kubernetes.cluster_memory
    query: avg(last_15m):avg:system.mem.pct_usable{kubernetescluster:cluster1.com} by {host} < .1
  - source: kubernetes.cluster_bytes_received
    definitions:
      notifications: '@custom-notification-channel'
```

However, if the monitor with the custom notification definition were defined first in the file, the `kubernetes.cluster_memory` monitor would have the notification set to `@custom-notification-channel`:

```yaml
definitions:
  notifications: "@foo"
monitors:
  - source: kubernetes.cluster_bytes_received
    definitions:
      notifications: '@custom-notification-channel'
  - source: kubernetes.cluster_memory
    query: avg(last_15m):avg:system.mem.pct_usable{kubernetescluster:cluster1.com} by {host} < .1
```
