### ISSUE TITLE
Defining a namespace for monitors is confusing

### ISSUE THREAD

**Issue by endzyme** [reactiveops/rodd#37]
The `containers_waiting_to_run` check names a namespace. This should probably alert per namespace that has waiting to run statuses instead of only being able to define a single namespace to check.

Example:
```yaml
# rodd.yaml
definitions:
  environment: production
  notifications: ""
  namespace: default
  cluster: someContext
dashboards:
   - source: kubernetes.resources
monitors:
  - source: kubernetes
exceptions:
  - kubernetes.cluster_bytes_received
```

This generates a `./datadog/production_containers_waiting_to_run.tf` which has: 

```hcl
...
  query = "min(last_30m):sum:kubernetes_state.container.waiting{kubernetescluster:someContext,namespace:default} > 1"
```

Should probably be setup to create a notification per namespace instead of pinning to one namespace.
